### ISSUE TITLE
Add way to customize metadata parsing, `metadata_parser`?

### ISSUE THREAD

**Issue by EmilStenstrom** [EmilStenstrom/conllu#32]
Lots of files have strange formats in their metadata. Adding a way to customize that parsing would likely help.

**Comment by EmilStenstrom** [comment]
What is a good API for this? Questions:

- Should there be just one parser per sentence? field_parsers are made to be one **per column**, so I'm not sure what people would expect here. Having one parser for all comment lines would make it possible to correlate things between multiple lines. I've never seen comments that would benefit from that, but would love to know if those cases exist...
- Should there be one parser per comment line? Maybe the first keyword on the line could trigger a parser with that name? If so, `# text = ...` would trigger the metadata text parser, and you could set the metadata_parser**s** the same way you set field_parsers.

I'm leaning toward the second way of doing it, mostly because it would rhyme well with how field_parsers work. When thinking about it, I think it would also simplify some of the code in parse_comment_line too, since is has special cases for things like "newpar" right now.

Anyone with ideas is free to jump in!

**Comment by flennic** [comment]
For the comments, my idea is the following:

Have one default parser that works according to specification. In addition, let the user also supply a custom parsing function for the comment fields. The user can choose, if he wants to have his custom parser instead of, before or after the default parser tried to process the line.

In my opinion that should add enough flexibility as a start.

> Should there be one parser per comment line?

Or maybe there can be supplied one parser that fails, if the default one doesn't work. Or custom supplied parsers also have a `match(sentence)` function which decides how the line in parsed. But there must be a way of prioritizing if user are allowed to add custom comment parsers, as multiple ones could return a "I want to parse this line" result.

Cheers
flennic

**Comment by EmilStenstrom** [comment]
> Have one default parser that works according to specification. 

Check! :)

> if **he** wants to have **his** custom parser

Mind you, there might be non-male users using conllu too... 👍 

> instead of, before or after the default parser tried to process the line.

I'm thinking that "instead of" would be enough for most users? That's how field_parsers work today: you replace the builtin functionality with your own. Do you have some use-case where this wouldn't work?

> Or maybe there can be supplied one parser that fails, if the default one doesn't work. 

How would you know that a parser failed though? Today all parsers fall back to just returning the string if it doesn't match, but sometimes that's just what you want...

> Or custom supplied parsers also have a `match(sentence)` function which decides how the line in parsed. But there must be a way of prioritizing if user are allowed to add custom comment parsers, as multiple ones could return a "I want to parse this line" result.

If we go with the "instead of" approach, there would be just one parser to use for the whole file. This means no need for prioritization.

**Comment by flennic** [comment]
> Mind you, there might be non-male users using conllu too... +1

When referring to he in that context, I always mean the generic he, which, of course, includes non-males. It is by no means meant in any contemptuous way. I personally just don't like writing "he and she" every time. I know some disagree with me on this.

> I'm thinking that "instead of" would be enough for most users? That's how field_parsers work today: you replace the builtin functionality with your own. Do you have some use-case where this wouldn't work?

Hm, I think in the end it will always work, but for example the use case I had [previously](https://github.com/flennic/conllu/commit/ca93d893a51ace62a01b5bca26648f32dda1b93f), only a short `if` was needed. In that case I had to supply the whole parser which means basically that I had to write the normal parsing logic again. That's why I had the idea. But to be honest, I am not sure which approach would be better here.

> How would you know that a parser failed though? Today all parsers fall back to just returning the string if it doesn't match, but sometimes that's just what you want...

A parser could have a `regex` that decides if the parser parses the line (if it doesn't fit the format, it "failed"). If no parser is found, the line is returned as it is (just a "string"). "Failed" is probably the wrong term, better a "I think I am able to parse this line". If a parser actually fails, it could either return the line as a string as it is now, or pass it on to the list of remaining parsers. But this whole concept might be a bit overkill and adds unnecessary complexity. 

> If we go with the "instead of" approach, there would be just one parser to use for the whole file. This means no need for prioritization.

That is true. Maybe it is a good idea to follow that approach as a start and only add more complexity, if more people require the complexer logic with priorities.

Regards
flennic

**Comment by EmilStenstrom** [comment]
Thanks for your thoughts! Here's an example of how it could work:

Given this metadata before a sentence:
```
# global.columns = ID FORM LEMMA UPOS XPOS FEATS HEAD DEPREL DEPS MISC
# newdoc id = mf920901-001
# newpar id = mf920901-001-p1
# sent_id = mf920901-001-p1s1A
# text = Slovenská ústava: pro i proti
# text_en = Slovak constitution: pros and cons
```

The default parser would have specific parsers for "global.columns", "newdoc id",  "newpar id",  "sent_id",  "text",  "text_[LANGAUGE]". Any file which just uses those standard fields would get parsed as:

```
{
    "global.columns": "ID FORM LEMMA UPOS XPOS FEATS HEAD DEPREL DEPS MISC",
    "newdoc id": "mf920901-001",  
    "newpar id": "mf920901-001-p1",  
    "sent_id": "mf920901-001-p1s1A",  
    "text": "Slovenská ústava: pro i proti",  
    "text_en": "Slovak constitution: pros and cons"
}
```

But say you wanted the global.columns field be parsed into a list instead. Then you would do:

```
parse(data, metadata_parsers={"global.columns": lambda key, value: (key, value.split())}
```

And get this instead:
```
{
    "global.columns": ["ID", "FORM", "LEMMA", "UPOS", "XPOS", "FEATS", "HEAD", "DEPREL", "DEPS", "MISC"],
    "newdoc id": "mf920901-001",  
    "newpar id": "mf920901-001-p1",  
    "sent_id": "mf920901-001-p1s1A",  
    "text": "Slovenská ústava: pro i proti",  
    "text_en": "Slovak constitution: pros and cons"
}
```

I think this would solve most cases, but not your specific one, as it doesn't have a name at all. 

I'm thinking you could have a special metadata field called "__fallback__", that triggers when none of the other parsers match. This means that your case could be written as:

```
parse(data, metadata_parsers={"__fallback__": lambda key, value: ("sentence-id", key)}
```

What do you think?

**Comment by flennic** [comment]
Seems like a good idea to me, also having a "fallback" metafield sounds useful!

**Comment by EmilStenstrom** [comment]
This is now released, and part of the latest version of conllu! I also wrote some documentation that you can read about how to customize parsing to your liking: https://github.com/EmilStenstrom/conllu#customizing-parsing-to-handle-strange-variations-of-conll-u

**Comment by flennic** [comment]
Thank your very much, that's a very neat implementation! :)
