### ISSUE TITLE
Adding new token to existing sentence

### ISSUE THREAD

**Issue by jheinecke** [EmilStenstrom/conllu#49]
Is it possible to modifiy a parsed Conllu Sentence? I tried to add a new token exploiting the fact that a sentence is a token list:

```
import conllu

data = """# sent_id = 1
1	the	the	DET	_	_	2	det	_	_
2	cat	cat	NOUN	_	_	3	nsubj	_	_
3	sleeps	sleep	VERB	_	_	0	root	_	_
"""

sentences = conllu.parse(data)
print(sentences [0].serialize())

newtoken = conllu.models.Token({"id":4, "form":"well", "head": 3, "deprel":"advmod"})
sentences[0].append(newtoken)

print(sentences [0].serialize()) # ERROR: Token "4' incorrectly serialized
```

Maybe this is not the best practice? (I haven't found any information, though)
But doing it this way the final output is incorrect, since my new token 4 was initialized only with id, form, head and deprel:

```
# sent_id = 1
1	the	the	DET	_	_	2	det	_	_
2	cat	cat	NOUN	_	_	3	nsubj	_	_
3	sleeps	sleep	VERB	_	_	0	root	_	_
4	well	3	advmod
```
Shouldn't `Token()`  initialize all fields with "_" to assure a correct serialisation?

**Comment by EmilStenstrom** [comment]
Hi @jheinecke,

You are right that the documentation in this area isn't great. Let me try to add so answers here:

* You are adding tokens the correct way. Since Token is a subclass of dict, you could append a dict directly, but it's probably safer to do it your way.
* The error you get is because you're not specifying all the required fields. Do you have a use-case where you don't want to add all the required fields, or how come you ended up there?
* Making Token initialize with "_" is tricky, because which fields to parse is configurable. This is to allow the parsing of custom conllu formats, which means you can specify custom fields as input to parse if you want. This means that each Token is independent, and doesn't know of other Tokens, or even which TokenList it's in. So if I changed Token to prefill with the default fields, that would break when using parse with custom fields...

I'm eager to know more about your use-case, to see how conllu can become easier to use!

**Comment by jheinecke** [comment]
I have a CoNLL-U file where (French)  words like "du" or "au" are correctly split in "de" "le" and "à" "le" but the multitoken word is absent. So I have

```
...
3	de	de	ADP	_	_	5	case	_	_
4	le	le	DET	_	_	5	det	_	_
6	pain	pain	NOUN	_	_	2	obj	_	_
```

and I want to produce the following

```
...
3-4	du	_	_	_	_	_	_	_	_
3	de	de	ADP	_	_	5	case	_	_
4	le	le	DET	_	_	5	det	_	_
6	pain	pain	NOUN	_	_	2	obj	_	_
```

and for pure laziness I thought it isn't necessary to add empty fields. If you do not want to initialize them. You could add a "_" in the serialisation method to avoid invalid CoNLL-U output?

**Comment by EmilStenstrom** [comment]
Ah, thanks for the context! That makes a lot of sense. While serializing, I guess we could get the fields from the first token in each tokenlist, and assume the fields will be the same for all tokens in that list. So when we encounter a Token with fewer fields, we could output a "_" as you suggested. Seems like a nice addition.

Is this something you would be willing to add as a PR, preferably with tests? :)

**Comment by jheinecke** [comment]
Cannot promise this, since I have to dive into your code to avoid causing more harm then good ...

**Comment by EmilStenstrom** [comment]
I'll work on this a bit on and off in the coming weeks. As a first simple step I changed TokenList contructor and tokenlist.append to optionally accept dicts instead of Tokens. It's a small fix, but improves the ergonomics slightly. This is out in conllu 4.3.1. More to come.

**Comment by EmilStenstrom** [comment]
I finally managed to complete this. I've reworked how this works in version 4.4 of conllu, and documentation is available here: https://github.com/EmilStenstrom/conllu#writing-data-back-to-a-tokenlist

Let me know how this works for you!
