### ISSUE TITLE
Cannot parse CoNNL-U Plus fields after reading file content

### ISSUE THREAD

**Issue by harisont** [EmilStenstrom/conllu#61]
It seems that if I write:

```python
with open("my.conllup") as file:
        content = file.read()
        plus_fields = conllu.parse_conllu_plus_fields(file)
```
`plus_fields` is equal to `None`, while if run `parse_conllu_plus_fields` _first_ and _then_ read the file everything works as expected.

**Comment by EmilStenstrom** [comment]
@harisont This is how Python works. When you call read() on a file pointer, that pointer moves to the end of what you just read. So to conllu this file looks like it's empty. What happens if you add file.seek(0) after you read the file, but before you parse the plus fields?

Also, why do you need to parse the fields separate? Is there some feature that's missing from conllu that you need to build yourself?

**Comment by harisont** [comment]
Sorry, you're completely right! I got too used to stateless reasoning :laughing:
